#!/usr/bin/env python3
"""
CUE Sheet, M3U8, Rekordbox XML, Traktor NML, and Audio Slicer Engine for Drop Agent.
Implements Red Book Standard CUE generation (75 fps), Rekordbox DJ_PLAYLISTS bridge,
Traktor NML collection export, and zero-crossing lossless audio slicing with micro-fades.
"""

import os
import re
import math
import subprocess
import urllib.parse
import xml.etree.ElementTree as ET
from xml.dom import minidom
from typing import List, Dict, Optional, Tuple

try:
    from fingerprinting.transition_detector import find_zero_crossing, TransitionDetector
except ImportError:
    import sys
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
    from fingerprinting.transition_detector import find_zero_crossing, TransitionDetector


def seconds_to_cue_time(seconds: float) -> str:
    """
    Converts seconds float to Red Book Standard MM:SS:FF format (75 frames per second).
    """
    total_frames = int(round(max(0.0, seconds) * 75))
    frames = total_frames % 75
    total_seconds = total_frames // 75
    minutes = total_seconds // 60
    secs = total_seconds % 60
    return f"{minutes:02d}:{secs:02d}:{frames:02d}"


def cue_time_to_seconds(cue_time: str) -> float:
    """
    Parses MM:SS:FF (or HH:MM:SS) string into seconds.
    """
    parts = [int(p) for p in cue_time.strip().split(":")]
    if len(parts) == 3:
        # MM:SS:FF
        return parts[0] * 60 + parts[1] + (parts[2] / 75.0)
    elif len(parts) == 2:
        return parts[0] * 60 + parts[1]
    return 0.0


def sanitize_cue_string(text: str) -> str:
    """Escapes quotes and cleans string for CUE sheet."""
    if not text:
        return ""
    return text.replace('"', "'").strip()


def generate_cue_sheet(
    album_title: str,
    performer: str,
    genre: str,
    audio_filename: str,
    tracks: List[Dict],
    output_path: Optional[str] = None,
    year: Optional[str] = None
) -> str:
    """
    Generates a Red Book Standard .cue file.
    """
    safe_album = sanitize_cue_string(album_title)
    safe_perf = sanitize_cue_string(performer or "Various Artists")
    safe_genre = sanitize_cue_string(genre or "Electronic")
    safe_year = year or "2026"

    # Determine file audio type
    ext = os.path.splitext(audio_filename)[1].lower()
    audio_type = "MP3"
    if ext in (".wav", ".wave"):
        audio_type = "WAVE"
    elif ext in (".flac",):
        audio_type = "FLAC"
    elif ext in (".aif", ".aiff"):
        audio_type = "AIFF"

    lines = [
        f'REM GENRE "{safe_genre}"',
        f'REM DATE "{safe_year}"',
        'REM COMMENT "Generated by Drop Agent 2.0 (Drops Music Intelligence)"',
        f'PERFORMER "{safe_perf}"',
        f'TITLE "{safe_album}"',
        f'FILE "{audio_filename}" {audio_type}'
    ]

    for idx, t in enumerate(tracks, start=1):
        num = t.get("track_num", idx)
        title = sanitize_cue_string(t.get("title", f"Track {num:02d}"))
        artist = sanitize_cue_string(t.get("artist", safe_perf))
        start_sec = t.get("start_time", 0.0)
        cue_index = seconds_to_cue_time(start_sec)
        camelot = t.get("camelot", "")
        bpm = t.get("bpm", "")

        lines.append(f'  TRACK {num:02d} AUDIO')
        lines.append(f'    TITLE "{title}"')
        lines.append(f'    PERFORMER "{artist}"')
        if camelot and camelot != "—" and camelot != "Unknown":
            lines.append(f'    REM KEY "{camelot}"')
        if bpm and bpm != "—":
            lines.append(f'    REM BPM "{bpm}"')
        lines.append(f'    INDEX 01 {cue_index}')

    cue_content = "\n".join(lines) + "\n"

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(cue_content)
        print(f"[CUE Generator] 📜 Generated Red Book CUE sheet: {output_path}")

    return cue_content


def generate_extended_m3u8(
    playlist_name: str,
    tracks: List[Dict],
    output_path: str,
    audio_files_dir: Optional[str] = None
) -> str:
    """
    Generates an extended M3U8 playlist with #EXTINF and Camelot/BPM annotations.
    """
    lines = [
        "#EXTM3U",
        f"#PLAYLIST:{playlist_name}"
    ]

    for idx, t in enumerate(tracks, start=1):
        num = t.get("track_num", idx)
        artist = t.get("artist", "Various Artists").strip()
        title = t.get("title", f"Track {num:02d}").strip()
        duration_sec = int(round(t.get("duration_seconds", 0.0)))
        if duration_sec <= 0:
            duration_sec = -1

        camelot = t.get("camelot", "")
        bpm = t.get("bpm", "")
        filename = t.get("filename")

        if not filename:
            filename = f"{num:02d}. {artist} - {title}.mp3".replace("/", "-")

        ext_info = f"#EXTINF:{duration_sec},{artist} - {title}"
        lines.append(ext_info)
        if camelot and camelot != "—":
            lines.append(f"#EXT-X-KEY:CAMELOT={camelot}")
        if bpm and bpm != "—":
            lines.append(f"#EXT-X-BPM:{bpm}")
        lines.append(filename)

    m3u_content = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(m3u_content)

    print(f"[CUE Generator] 📜 Generated extended M3U8: {output_path}")
    return m3u_content


def generate_rekordbox_xml(
    album_title: str,
    performer: str,
    genre: str,
    audio_file_path: str,
    tracks: List[Dict],
    output_path: Optional[str] = None,
    total_mix_duration: Optional[float] = None
) -> str:
    """
    Generates Pioneer Rekordbox DJ_PLAYLISTS XML (v1.0.0) format with Beatgrid,
    average BPM, Camelot Key and Hot Cue / Memory Cue position markers.
    """
    root = ET.Element("DJ_PLAYLISTS", Version="1.0.0")
    ET.SubElement(root, "PRODUCT", Name="rekordbox", Version="7.0.0", Company="AlphaTheta")

    collection = ET.SubElement(root, "COLLECTION", Entries=str(len(tracks) + 1 if os.path.exists(audio_file_path) else len(tracks)))

    # Compute average BPM
    valid_bpms = [float(t["bpm"]) for t in tracks if t.get("bpm") and str(t["bpm"]) != "—" and float(t["bpm"]) > 0]
    avg_bpm = round(sum(valid_bpms) / len(valid_bpms), 2) if valid_bpms else 124.0

    initial_camelot = tracks[0].get("camelot", "8A") if tracks else "8A"
    if initial_camelot == "—" or not initial_camelot:
        initial_camelot = "8A"

    abs_audio_path = os.path.abspath(audio_file_path)
    file_url = f"file://localhost{urllib.parse.quote(abs_audio_path)}"

    mix_duration = total_mix_duration
    if not mix_duration:
        if tracks:
            mix_duration = max(t.get("end_time", 0.0) for t in tracks)
        else:
            mix_duration = 3600.0

    # 1. Full Mix Track Entry with Cues
    mix_track_el = ET.SubElement(
        collection,
        "TRACK",
        TrackID="1",
        Name=album_title,
        Artist=performer or "Various Artists",
        Album=album_title,
        Genre=genre or "Electronic",
        TotalTime=str(int(mix_duration)),
        AverageBpm=f"{avg_bpm:.2f}",
        Tonality=initial_camelot,
        Location=file_url
    )
    ET.SubElement(mix_track_el, "TEMPO", Inizio="0.000", Bpm=f"{avg_bpm:.2f}", Metro="4/4", Battito="1")

    # Add Hot Cues and Memory Cues for each track inside the full mix
    for idx, t in enumerate(tracks, start=1):
        num = t.get("track_num", idx)
        title = t.get("title", f"Track {num:02d}")
        artist = t.get("artist", performer)
        start_sec = max(0.0, float(t.get("start_time", 0.0)))
        marker_name = f"{num:02d}. {artist} - {title}"

        # Hot Cue (Num 0..7 for first 8 tracks, memory cues for rest)
        hotcue_num = str(idx - 1) if idx <= 8 else "-1"
        ET.SubElement(
            mix_track_el,
            "POSITION_MARK",
            Name=marker_name,
            Type="0",
            Start=f"{start_sec:.3f}",
            Num=hotcue_num,
            Red="240",
            Green="80",
            Blue="40"
        )

    # 2. Individual Track Entries (if sliced)
    track_id_counter = 2
    for t in tracks:
        t_artist = t.get("artist", performer)
        t_title = t.get("title", "")
        t_camelot = t.get("camelot", "8A")
        t_bpm = float(t.get("bpm", avg_bpm)) if t.get("bpm") and str(t.get("bpm")) != "—" else avg_bpm
        t_dur = int(round(float(t.get("duration_seconds", 300.0))))
        t_filename = t.get("filename", f"{t.get('track_num', 1):02d}. {t_artist} - {t_title}.mp3")
        t_path = os.path.join(os.path.dirname(abs_audio_path), t_filename)
        t_url = f"file://localhost{urllib.parse.quote(os.path.abspath(t_path))}"

        t_el = ET.SubElement(
            collection,
            "TRACK",
            TrackID=str(track_id_counter),
            Name=t_title,
            Artist=t_artist,
            Album=album_title,
            Genre=genre or "Electronic",
            TotalTime=str(t_dur),
            AverageBpm=f"{t_bpm:.2f}",
            Tonality=t_camelot if t_camelot != "—" else "8A",
            Location=t_url
        )
        ET.SubElement(t_el, "TEMPO", Inizio="0.000", Bpm=f"{t_bpm:.2f}", Metro="4/4", Battito="1")
        ET.SubElement(t_el, "POSITION_MARK", Name="Intro", Type="0", Start="0.000", Num="0", Red="40", Green="160", Blue="240")
        track_id_counter += 1

    # Playlists structure
    playlists = ET.SubElement(root, "PLAYLISTS")
    root_node = ET.SubElement(playlists, "NODE", Type="0", Name="ROOT")
    set_node = ET.SubElement(root_node, "NODE", Type="1", Name=album_title, KeyType="0", Entries=str(track_id_counter - 1))
    for k in range(1, track_id_counter):
        ET.SubElement(set_node, "TRACK", Key=str(k))

    # Format pretty XML string
    rough_string = ET.tostring(root, encoding="utf-8")
    parsed = minidom.parseString(rough_string)
    pretty_xml = parsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(pretty_xml)
        print(f"[Rekordbox Exporter] 🎛️  Generated Rekordbox XML: {output_path}")

    return pretty_xml


def generate_traktor_nml(
    album_title: str,
    performer: str,
    genre: str,
    audio_file_path: str,
    tracks: List[Dict],
    output_path: Optional[str] = None,
    total_mix_duration: Optional[float] = None
) -> str:
    """
    Generates Native Instruments Traktor Pro Collection NML format.
    """
    root = ET.Element("NML", VERSION="19")
    ET.SubElement(root, "HEAD", COMPANY="native-instruments.de", PROGRAM="Traktor")

    collection = ET.SubElement(root, "COLLECTION", ENTRIES="1")

    abs_path = os.path.abspath(audio_file_path)
    file_dir = os.path.dirname(abs_path).replace("/", "/:") + "/:"
    file_name = os.path.basename(abs_path)

    valid_bpms = [float(t["bpm"]) for t in tracks if t.get("bpm") and str(t["bpm"]) != "—" and float(t["bpm"]) > 0]
    avg_bpm = round(sum(valid_bpms) / len(valid_bpms), 2) if valid_bpms else 124.0

    initial_camelot = tracks[0].get("camelot", "8A") if tracks else "8A"
    mix_duration = int(total_mix_duration or 3600)

    entry = ET.SubElement(collection, "ENTRY", MODIFIED_DATE="2026/8/31", TITLE=album_title, ARTIST=performer or "Various Artists")
    ET.SubElement(entry, "LOCATION", DIR=file_dir, FILE=file_name, VOLUME="/", VOLUMEID="/")
    ET.SubElement(entry, "INFO", BITRATE="320000", GENRE=genre or "Electronic", PLAYTIME=str(mix_duration), KEY=initial_camelot)
    ET.SubElement(entry, "TEMPO", BPM=f"{avg_bpm:.2f}", BPM_QUALITY="100.0")

    for idx, t in enumerate(tracks, start=1):
        num = t.get("track_num", idx)
        title = t.get("title", f"Track {num:02d}")
        start_ms = float(t.get("start_time", 0.0)) * 1000.0
        hotcue_idx = (idx - 1) if idx <= 8 else -1
        ET.SubElement(
            entry,
            "CUE_V2",
            NAME=f"{num:02d}. {title}",
            TYPE="0",
            START=f"{start_ms:.1f}",
            LEN="0.0",
            REPEATS="-1",
            HOTCUE=str(hotcue_idx)
        )

    rough_string = ET.tostring(root, encoding="utf-8")
    parsed = minidom.parseString(rough_string)
    pretty_nml = parsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(pretty_nml)
        print(f"[Traktor Exporter] 🎛️  Generated Traktor NML: {output_path}")

    return pretty_nml


def slice_audio_mix(
    audio_path: str,
    tracks: List[Dict],
    output_dir: str,
    micro_fade_ms: int = 50,
    zero_crossing: bool = True,
    album_title: str = "",
    genre: str = "Deep House"
) -> List[str]:
    """
    Lossless / high-quality audio slicing of a full mix into individual tracks with FFmpeg.
    Aligns cut points on zero-crossings and applies transparent micro-fades to prevent clicks.
    """
    if not os.path.exists(audio_path):
        print(f"[Audio Slicer] ❌ Full mix audio file not found: {audio_path}")
        return []

    os.makedirs(output_dir, exist_ok=True)
    detector = TransitionDetector() if zero_crossing else None
    generated_files = []

    fade_s = micro_fade_ms / 1000.0

    print(f"[Audio Slicer] ✂️ Slicing {len(tracks)} tracks from {os.path.basename(audio_path)}...")

    for idx, t in enumerate(tracks, start=1):
        num = t.get("track_num", idx)
        artist = t.get("artist", "Various Artists").strip() or "Various Artists"
        title = t.get("title", f"Track {num:02d}").strip()
        start_time = float(t.get("start_time", 0.0))
        end_time = float(t.get("end_time", start_time + 300.0))

        if detector and start_time > 0.0:
            start_time = detector.align_to_nearest_zero_crossing(audio_path, start_time)
        if detector and end_time > start_time:
            end_time = detector.align_to_nearest_zero_crossing(audio_path, end_time)

        duration = max(1.0, end_time - start_time)
        out_filename = f"{num:02d}. {artist} - {title}.mp3".replace("/", "-")
        out_path = os.path.join(output_dir, out_filename)

        camelot = t.get("camelot", "")
        key_name = t.get("key", "")
        bpm = t.get("bpm", "")

        metadata_args = [
            "-metadata", f"title={title}",
            "-metadata", f"artist={artist}",
            "-metadata", f"album={album_title or os.path.basename(output_dir)}",
            "-metadata", f"track={num}",
            "-metadata", f"genre={genre}",
        ]
        if camelot and camelot != "—":
            metadata_args.extend(["-metadata", f"initialkey={camelot}", "-metadata", f"KEY={camelot}"])
        if bpm and bpm != "—":
            metadata_args.extend(["-metadata", f"TBPM={int(round(float(bpm)))}", "-metadata", f"BPM={bpm}"])

        # Micro-fades to eliminate digital transients at boundaries
        af_filter = f"afade=t=in:ss=0:d={fade_s},afade=t=out:st={duration - fade_s:.3f}:d={fade_s}"

        cmd = [
            "ffmpeg",
            "-y",
            "-ss", f"{start_time:.3f}",
            "-t", f"{duration:.3f}",
            "-i", audio_path,
            "-af", af_filter,
            "-c:a", "libmp3lame",
            "-b:a", "320k",
            *metadata_args,
            out_path
        ]

        try:
            subprocess.run(cmd, capture_output=True, check=True)
            t["filename"] = out_filename
            generated_files.append(out_path)
            print(f"[Audio Slicer] ✅ Sliced track {num:02d}: {out_filename} ({duration:.1f}s)")
        except Exception as e:
            print(f"[Audio Slicer] ⚠️ Failed slicing track {num:02d}: {e}")

    return generated_files


def export_all_dj_formats(
    target_dir: str,
    album_title: str,
    genre: str,
    full_mix_filename: str,
    tracks: List[Dict],
    performer: str = "Various Artists",
    slice_audio: bool = False
) -> Dict[str, str]:
    """
    Convenience function that exports all DJ formats:
    - Standard Red Book .CUE sheet
    - Extended .M3U8 playlist
    - Rekordbox XML (DJ_PLAYLISTS)
    - Traktor Pro NML
    - Optional zero-crossing lossless audio slicing
    """
    full_mix_path = os.path.join(target_dir, full_mix_filename)
    safe_title = album_title.replace("/", "-")

    cue_path = os.path.join(target_dir, f"{safe_title}.cue")
    m3u8_path = os.path.join(target_dir, f"{safe_title}.m3u8")
    rekordbox_path = os.path.join(target_dir, "rekordbox.xml")
    traktor_path = os.path.join(target_dir, "traktor.nml")

    results = {}

    if slice_audio and os.path.exists(full_mix_path):
        sliced = slice_audio_mix(
            audio_path=full_mix_path,
            tracks=tracks,
            output_dir=target_dir,
            album_title=album_title,
            genre=genre
        )
        results["sliced_tracks"] = str(len(sliced))

    # 1. CUE
    generate_cue_sheet(
        album_title=album_title,
        performer=performer,
        genre=genre,
        audio_filename=full_mix_filename,
        tracks=tracks,
        output_path=cue_path
    )
    results["cue"] = cue_path

    # 2. M3U8
    generate_extended_m3u8(
        playlist_name=album_title,
        tracks=tracks,
        output_path=m3u8_path,
        audio_files_dir=target_dir
    )
    results["m3u8"] = m3u8_path

    # 3. Rekordbox XML
    generate_rekordbox_xml(
        album_title=album_title,
        performer=performer,
        genre=genre,
        audio_file_path=full_mix_path,
        tracks=tracks,
        output_path=rekordbox_path
    )
    results["rekordbox"] = rekordbox_path

    # 4. Traktor NML
    generate_traktor_nml(
        album_title=album_title,
        performer=performer,
        genre=genre,
        audio_file_path=full_mix_path,
        tracks=tracks,
        output_path=traktor_path
    )
    results["traktor"] = traktor_path

    return results
